import { Trek, BlogPost } from './types';

export const TREKS: Trek[] = [
  {
    id: 'kalsubai',
    name: 'Kalsubai Peak Trek',
    tagline: 'The Everest of Maharashtra',
    description: 'Kalsubai is the highest peak of Maharashtra. It offers a breathtaking view of the Sahyadri ranges and the Bhandardara dam.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/f1/d1/9e/f1d19efc1beee8b7b4497e6de0bcdf07.jpg',
    gallery: [
      'https://i.pinimg.com/736x/f8/5f/ec/f85fec4df60b829db34ea0c5b4518248.jpg',
      'https://i.pinimg.com/736x/11/39/3c/11393ce8bcb159aa8dd3d8feb4307d04.jpg',
    ],
    maxAltitude: '5400 ft',
    bestTime: 'June to February',
    highlights: ['Highest Peak of Maharashtra', 'Panoramic View of Sahyadris', 'Bhandardara Dam View'],
    itinerary: [
      { day: 1, title: 'Base Village to Peak', description: 'Start early from Bari village, climb the ladders, and reach the summit.' }
    ],
    fitnessLevel: 'Moderate fitness required. Good for beginners with stamina.',
    packingList: ['Trekking shoes', '2L Water', 'Raincoat (Monsoon)', 'Torch'],
    weather: { temp: '22°C', condition: 'Cloudy' },
    coordinates: [19.6015, 73.7096],
    route: [
      [19.6105, 73.7196], // Bari Village
      [19.6055, 73.7146], // Ladder 1
      [19.6015, 73.7096]  // Summit
    ],
    waypoints: [
      { name: 'Bari Village', coordinates: [19.6105, 73.7196], type: 'base', description: 'Starting point of the trek' },
      { name: 'Ladder Section', coordinates: [19.6055, 73.7146], type: 'view', description: 'Steep iron ladders' },
      { name: 'Kalsubai Temple', coordinates: [19.6015, 73.7096], type: 'peak', description: 'Highest point in Maharashtra' }
    ]
  },
  {
    id: 'harishchandragad',
    name: 'Harishchandragad Trek',
    tagline: 'The King of Forts',
    description: 'Harishchandragad is a hill fort in the Ahmednagar district of Maharashtra. It is famous for its Konkan Kada (Konkan Cliff) and Kedareshwar Cave.',
    price: 11999,
    duration: '7 Days',
    difficulty: 'Hard',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/1200x/a0/57/98/a05798b917e90ca9ac685be0c17e7e8f.jpg',
    gallery: [
      'https://i.pinimg.com/736x/f4/11/f4/f411f448d24278c1494ecc2fdd1d6f65.jpg'
    ],
    maxAltitude: '4670 ft',
    bestTime: 'August to March',
    highlights: ['Konkan Kada View', 'Kedareshwar Cave', 'Taramati Peak'],
    itinerary: [
      { day: 1, title: 'Base to Kokankada', description: 'Trek from Khireshwar or Pachnai to reach the plateau.' },
      { day: 2, title: 'Explore and Descend', description: 'Visit Taramati peak and descend back to base.' }
    ],
    fitnessLevel: 'High endurance required. Not recommended for first-timers.',
    packingList: ['Sleeping bag', 'Full sleeves clothes', 'Energy bars', 'First aid kit'],
    weather: { temp: '18°C', condition: 'Mist' },
    coordinates: [19.3854, 73.7745],
    route: [
      [19.3954, 73.7845], // Pachnai Village
      [19.3904, 73.7795], // Harishchandreshwar Temple
      [19.3854, 73.7745]  // Konkan Kada
    ],
    waypoints: [
      { name: 'Pachnai Village', coordinates: [19.3954, 73.7845], type: 'base', description: 'Easiest base village' },
      { name: 'Kedareshwar Cave', coordinates: [19.3904, 73.7795], type: 'view', description: 'Ancient cave with massive Shiva Linga' },
      { name: 'Konkan Kada', coordinates: [19.3854, 73.7745], type: 'view', description: 'Semicircular cliff with breathtaking view' }
    ]
  },
  {
    id: 'rajmachi',
    name: 'Rajmachi Fort Trek',
    tagline: 'The Twin Fort Adventure',
    description: 'Rajmachi is a popular trekking destination near Lonavala. It consists of two twin forts, Shrivardhan and Manaranjan.',
    price: 4999,
    duration: '3 Days',
    difficulty: 'Easy',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/1200x/f9/a0/a4/f9a0a4f0b32d751abed0d82aabc2fa63.jpg',
    gallery: [
      'https://i.pinimg.com/736x/22/49/23/2249231d8c9671e6978c1b991cddd48c.jpg'
    ],
    maxAltitude: '2710 ft',
    bestTime: 'June to September (Fireflies in May)',
    highlights: ['Twin Forts', 'Fireflies Festival', 'Lush Greenery'],
    itinerary: [
      { day: 1, title: 'Lonavala to Rajmachi', description: 'Walk through the forest trail from Lonavala or trek from Kondivade.' }
    ],
    fitnessLevel: 'Basic fitness. Great for beginners and families.',
    packingList: ['Comfortable shoes', 'Cap', 'Sunscreen', 'Water'],
    weather: { temp: '25°C', condition: 'Sunny' },
    coordinates: [18.8286, 73.3951],
    route: [
      [18.7586, 73.4051], // Lonavala
      [18.8086, 73.4001], // Udhewadi
      [18.8286, 73.3951]  // Shrivardhan Fort
    ],
    waypoints: [
      { name: 'Lonavala Start', coordinates: [18.7586, 73.4051], type: 'base', description: 'Starting point from Lonavala' },
      { name: 'Udhewadi Village', coordinates: [18.8086, 73.4001], type: 'camp', description: 'Base village for the forts' },
      { name: 'Shrivardhan Fort', coordinates: [18.8286, 73.3951], type: 'peak', description: 'Higher of the two forts' }
    ]
  },
  {
    id: 'lohagad',
    name: 'Lohagad Fort Trek',
    tagline: 'The Iron Fort',
    description: 'Lohagad is one of the many hill forts of Maharashtra state in India. Situated close to the hill station Lonavala and 52 km northwest of Pune, Lohagad rises to an elevation of 1,033 m above sea level.',
    price: 4999,
    duration: '3 Days',
    difficulty: 'Easy',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/d0/4e/cc/d04ecce44038b3f41e6024184bc7cb3b.jpg',
    gallery: ['https://i.pinimg.com/1200x/de/5f/1b/de5f1b01c826c08b17a6b3335d24dbf9.jpg'],
    maxAltitude: '3389 ft',
    bestTime: 'Year round (Monsoon is best)',
    highlights: ['Vinchu Kata Point', 'Reverse Waterfall', 'Ancient Gates'],
    itinerary: [{ day: 1, title: 'Base to Fort', description: 'Easy climb via stone steps from Malavli station or Lohagadwadi.' }],
    fitnessLevel: 'Basic fitness. Suitable for all ages.',
    packingList: ['Water', 'Snacks', 'Raincoat'],
    weather: { temp: '24°C', condition: 'Windy' },
    coordinates: [18.7042, 73.4831],
    route: [[18.7142, 73.4931], [18.7042, 73.4831]],
    waypoints: [{ name: 'Lohagadwadi', coordinates: [18.7142, 73.4931], type: 'base', description: 'Base village' }]
  },
  {
    id: 'visapur',
    name: 'Visapur Fort Trek',
    tagline: 'The Waterfall Staircase',
    description: 'Visapur Fort is larger and at a higher elevation than its twin fort, Lohagad. It is famous for the staircase that turns into a waterfall during monsoons.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/16/95/7d/16957df3eee0e7f3af2e510c4e62f336.jpg',
    gallery: ['https://i.pinimg.com/1200x/9d/4f/ae/9d4faebf812ef5f2f08cc46c5779ffbe.jpg'],
    maxAltitude: '3556 ft',
    bestTime: 'Monsoon (July to September)',
    highlights: ['Waterfall Trek', 'Large Plateau', 'Ancient Caves'],
    itinerary: [{ day: 1, title: 'Trek through Waterfalls', description: 'Climb up the rocky path which becomes a stream in monsoon.' }],
    fitnessLevel: 'Moderate. Requires good grip shoes.',
    packingList: ['Extra clothes', 'Waterproof bag', 'Grip shoes'],
    weather: { temp: '20°C', condition: 'Rainy' },
    coordinates: [18.7186, 73.4864],
    route: [[18.7286, 73.4964], [18.7186, 73.4864]],
    waypoints: [{ name: 'Visapur Base', coordinates: [18.7286, 73.4964], type: 'base', description: 'Start of the trail' }]
  },
  {
    id: 'sinhagad',
    name: 'Sinhagad Fort Trek',
    tagline: 'The Lion Fort',
    description: 'Sinhagad is a hill fortress located at around 31 km southwest of the city of Pune, India. It was previously known as Kondhana.',
    price: 4999,
    duration: '3 Days',
    difficulty: 'Easy',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/da/b5/17/dab517c80a2c7b2329515ad2a4638916.jpg',
    gallery: ['https://i.pinimg.com/736x/24/78/a7/2478a797c2cbb23cd7535fbd5b739167.jpg'],
    maxAltitude: '4320 ft',
    bestTime: 'Year round',
    highlights: ['Pithla Bhakri Food', 'Tanaji Malusare Memorial', 'Pune City View'],
    itinerary: [{ day: 1, title: 'Base to Top', description: 'A pleasant walk from Atkarwadi base village.' }],
    fitnessLevel: 'Basic. Very popular for morning walks.',
    packingList: ['Water', 'Sunscreen', 'Walking shoes'],
    weather: { temp: '26°C', condition: 'Clear' },
    coordinates: [18.3663, 73.7554],
    route: [[18.3763, 73.7654], [18.3663, 73.7554]],
    waypoints: [{ name: 'Atkarwadi', coordinates: [18.3763, 73.7654], type: 'base', description: 'Main base village' }]
  },
  {
    id: 'torna',
    name: 'Torna Fort Trek',
    tagline: 'The Highest Fort in Pune',
    description: 'Torna Fort, also known as Prachandagad, is a large fort located in Pune district, Maharashtra. It was the first fort captured by Shivaji Maharaj.',
    price: 11999,
    duration: '7 Days',
    difficulty: 'Hard',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/37/e7/7f/37e77fc4901434f606dacbfab39d2546.jpg',
    gallery: ['https://i.pinimg.com/736x/f3/49/c9/f349c93d4c20a7b1c5fd67dac642faa7.jpg'],
    maxAltitude: '4603 ft',
    bestTime: 'September to March',
    highlights: ['Zunjar Machi', 'Budhla Machi', 'Panoramic views'],
    itinerary: [{ day: 1, title: 'Velhe to Torna', description: 'Steep climb from Velhe village.' }],
    fitnessLevel: 'High. Steep slopes and rocky patches.',
    packingList: ['Sturdy boots', '3L Water', 'Energy snacks'],
    weather: { temp: '22°C', condition: 'Windy' },
    coordinates: [18.2764, 73.6214],
    route: [[18.2864, 73.6314], [18.2764, 73.6214]],
    waypoints: [{ name: 'Velhe', coordinates: [18.2864, 73.6314], type: 'base', description: 'Base village' }]
  },
  {
    id: 'raigad',
    name: 'Raigad Fort Trek',
    tagline: 'The Capital of Maratha Empire',
    description: 'Raigad is a hill fort situated in the Mahad, Raigad district of Maharashtra. It was the capital of the Maratha Empire.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/94/bd/98/94bd985df40728032bb217159ac337b6.jpg',
    gallery: ['https://i.pinimg.com/1200x/32/59/b6/3259b65bf809cfa97ff356ed81e0b553.jpg'],
    maxAltitude: '2700 ft',
    bestTime: 'Year round',
    highlights: ['Takmak Tok', 'Shivaji Maharaj Samadhi', 'Ropeway Experience'],
    itinerary: [{ day: 1, title: 'Ascent to Capital', description: 'Climb 1700+ steps or take the ropeway.' }],
    fitnessLevel: 'Moderate. Many steps to climb.',
    packingList: ['Water', 'Hat', 'Comfortable shoes'],
    weather: { temp: '28°C', condition: 'Humid' },
    coordinates: [18.2347, 73.4464],
    route: [[18.2447, 73.4564], [18.2347, 73.4464]],
    waypoints: [{ name: 'Raigad Base', coordinates: [18.2447, 73.4564], type: 'base', description: 'Lower station' }]
  },
  {
    id: 'pratapgad',
    name: 'Pratapgad Fort Trek',
    tagline: 'The Valour of Shivaji Maharaj',
    description: 'Pratapgad is a hill fort located in Satara district, Maharashtra. It is famous for the Battle of Pratapgad between Shivaji Maharaj and Afzal Khan.',
    price: 4999,
    duration: '3 Days',
    difficulty: 'Easy',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/1e/a9/b8/1ea9b896e17a45d6ac2654c2f9cc40d2.jpg',
    gallery: ['https://i.pinimg.com/736x/a5/64/4e/a5644eee745e9c0747e3ae153f5a421c.jpg'],
    maxAltitude: '3543 ft',
    bestTime: 'Year round',
    highlights: ['Afzal Khan Tomb', 'Bhavani Temple', 'Mahabaleshwar View'],
    itinerary: [{ day: 1, title: 'Explore the Fort', description: 'Easy walk through the well-maintained fort complex.' }],
    fitnessLevel: 'Basic. Suitable for families.',
    packingList: ['Water', 'Camera', 'Walking shoes'],
    weather: { temp: '22°C', condition: 'Pleasant' },
    coordinates: [17.9314, 73.5814],
    route: [[17.9414, 73.5914], [17.9314, 73.5814]],
    waypoints: [{ name: 'Pratapgad Parking', coordinates: [17.9414, 73.5914], type: 'base', description: 'Main entrance' }]
  },
  {
    id: 'ratangad',
    name: 'Ratangad Fort Trek',
    tagline: 'The Jewel of Sahyadris',
    description: 'Ratangad is a fort in Ratan Wadi, Maharashtra, overlooking the Bhandardara dam. The fort is about 2000 years old.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/dd/bf/ca/ddbfcabe462d5c8120a91aff9115938f.jpg',
    gallery: ['https://i.pinimg.com/736x/3b/ab/be/3babbe9b79408304cb2c428fa42c8a7a.jpg'],
    maxAltitude: '4255 ft',
    bestTime: 'October to February',
    highlights: ['Nedhe (Eye of the Needle)', 'Amrutheshwar Temple', 'Bhandardara View'],
    itinerary: [{ day: 1, title: 'Ratanwadi to Peak', description: 'Trek through the forest and climb the ladders.' }],
    fitnessLevel: 'Moderate. Some steep ladder sections.',
    packingList: ['Headlamp', 'Water', 'Energy bars'],
    weather: { temp: '18°C', condition: 'Cool' },
    coordinates: [19.5164, 73.7114],
    route: [[19.5264, 73.7214], [19.5164, 73.7114]],
    waypoints: [{ name: 'Ratanwadi', coordinates: [19.5264, 73.7214], type: 'base', description: 'Base village' }]
  },
  {
    id: 'harihar',
    name: 'Harihar Fort Trek',
    tagline: 'The Vertical Staircase',
    description: 'Harihar fort is located in the Nashik district of Maharashtra. It is famous for its almost vertical rock-cut steps.',
    price: 11999,
    duration: '7 Days',
    difficulty: 'Hard',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/1200x/63/60/11/6360118eaf3b7cb750b5c151fffc9f47.jpg',
    gallery: ['https://i.pinimg.com/736x/fd/6b/e2/fd6be288b8d2b898e35e3befd50a5e6e.jpg'],
    maxAltitude: '3676 ft',
    bestTime: 'September to February',
    highlights: ['Vertical Rock-cut Steps', 'Prism-like Shape', 'Trimbakeshwar Range View'],
    itinerary: [{ day: 1, title: 'The Vertical Climb', description: 'Start from Nirgudpada and climb the iconic steps.' }],
    fitnessLevel: 'High. Not for those with fear of heights.',
    packingList: ['Grip shoes', 'Water', 'Gloves'],
    weather: { temp: '25°C', condition: 'Sunny' },
    coordinates: [19.9034, 73.4714],
    route: [[19.9134, 73.4814], [19.9034, 73.4714]],
    waypoints: [{ name: 'Nirgudpada', coordinates: [19.9134, 73.4814], type: 'base', description: 'Base village' }]
  },
  {
    id: 'bhimashankar',
    name: 'Bhimashankar Trek',
    tagline: 'Through the Wildlife Sanctuary',
    description: 'Bhimashankar is home to one of the twelve Jyotirlingas and a wildlife sanctuary known for the Giant Indian Squirrel.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/1200x/18/58/b0/1858b020877ee9e6df3bbaa43b21a7b2.jpg',
    gallery: ['https://i.pinimg.com/736x/44/3d/fa/443dfab0cc7d6f0e9aa83a3e4b300392.jpg'],
    maxAltitude: '3250 ft',
    bestTime: 'August to March',
    highlights: ['Jyotirlinga Temple', 'Shekru (Giant Squirrel)', 'Gupt Bhimashankar'],
    itinerary: [{ day: 1, title: 'Shidi Ghat or Ganesh Ghat', description: 'Trek through the dense forest of the sanctuary.' }],
    fitnessLevel: 'Moderate. Long walk through the forest.',
    packingList: ['Full sleeves', 'Insect repellent', 'Water'],
    weather: { temp: '20°C', condition: 'Misty' },
    coordinates: [19.0714, 73.5314],
    route: [[19.0814, 73.5414], [19.0714, 73.5314]],
    waypoints: [{ name: 'Khandas', coordinates: [19.0814, 73.5414], type: 'base', description: 'Base village' }]
  },
  {
    id: 'devkund',
    name: 'Devkund Waterfall Trek',
    tagline: 'The Hidden Blue Lagoon',
    description: 'Devkund is a confluence of three rivers and is believed to be the origin of Kundalika River. It is a hidden gem near Bhira.',
    price: 4999,
    duration: '3 Days',
    difficulty: 'Easy',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/1200x/8e/e9/89/8ee9897b7b5f035e6c08763abec13ea4.jpg',
    gallery: ['https://i.pinimg.com/1200x/2c/38/da/2c38da07ff3cc6df9e23b2f34180f3a6.jpg'],
    maxAltitude: '2000 ft',
    bestTime: 'September to January',
    highlights: ['Crystal Clear Water', 'Dense Forest Walk', 'Tamhini Ghat View'],
    itinerary: [{ day: 1, title: 'Forest Walk to Fall', description: 'A flat trail through the forest leading to the waterfall.' }],
    fitnessLevel: 'Basic. Mostly flat trail.',
    packingList: ['Extra clothes', 'Waterproof bag', 'Sandals'],
    weather: { temp: '26°C', condition: 'Humid' },
    coordinates: [18.4514, 73.3114],
    route: [[18.4614, 73.3214], [18.4514, 73.3114]],
    waypoints: [{ name: 'Bhira Dam', coordinates: [18.4614, 73.3214], type: 'base', description: 'Starting point' }]
  },
  {
    id: 'andharban',
    name: 'Andharban Jungle Trek',
    tagline: 'The Dark Forest',
    description: 'Andharban, by its name, means a dark dense forest. It is a descending trek from Tamhini Ghat to Bhira Dam.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/de/38/ab/de38ab784634328a86343ef0aaa46f70.jpg',
    gallery: ['https://i.pinimg.com/736x/1a/dc/26/1adc26052e3691ff7f9b6b566c154fb6.jpg'],
    maxAltitude: '2100 ft',
    bestTime: 'Monsoon (July to September)',
    highlights: ['Dense Canopy', 'Multiple Waterfalls', 'Kundalika Valley View'],
    itinerary: [{ day: 1, title: 'The Forest Descent', description: 'Start from Pimpri and walk through the dense forest.' }],
    fitnessLevel: 'Moderate. Long descent can be hard on knees.',
    packingList: ['Raincoat', 'Extra socks', 'Water'],
    weather: { temp: '22°C', condition: 'Rainy' },
    coordinates: [18.4814, 73.3514],
    route: [[18.4914, 73.3614], [18.4814, 73.3514]],
    waypoints: [{ name: 'Pimpri', coordinates: [18.4914, 73.3614], type: 'base', description: 'Starting point' }]
  },
  {
    id: 'sandhan',
    name: 'Sandhan Valley Trek',
    tagline: 'The Valley of Shadows',
    description: 'Sandhan Valley is a beautiful water carved valley in the Sahyadri mountains. It is a unique experience of trekking through a narrow gorge.',
    price: 11999,
    duration: '7 Days',
    difficulty: 'Hard',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/1200x/89/78/d4/8978d4435df2108240b9bcb7359ebf04.jpg',
    gallery: ['https://i.pinimg.com/736x/03/c9/77/03c9779309bcd50a476b32dbcd3ce3dd.jpg'],
    maxAltitude: '3000 ft',
    bestTime: 'November to May',
    highlights: ['Deep Gorge Walk', 'Rappelling', 'Camping under Stars'],
    itinerary: [
      { day: 1, title: 'Valley Descent', description: 'Start from Samrad and descend through the narrow valley.' },
      { day: 2, title: 'Exit to Dehne', description: 'Trek towards Dehne village and return.' }
    ],
    fitnessLevel: 'High. Involves rappelling and long walks on boulders.',
    packingList: ['Headlamp', 'Full sleeves', 'Sturdy boots'],
    weather: { temp: '15°C', condition: 'Cool' },
    coordinates: [19.5214, 73.6814],
    route: [[19.5314, 73.6914], [19.5214, 73.6814]],
    waypoints: [{ name: 'Samrad', coordinates: [19.5314, 73.6914], type: 'base', description: 'Base village' }]
  },
  {
    id: 'vasota',
    name: 'Vasota Fort Trek',
    tagline: 'The Jungle Fortress',
    description: 'Vasota is a fort located in Satara district. It is surrounded by the Koyna Wildlife Sanctuary and is accessible only by boat.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/6b/05/e2/6b05e263dce84a8375bacca48411f0e8.jpg',
    gallery: ['https://i.pinimg.com/736x/44/94/b1/4494b1f63e87dc233efb26c2233b4617.jpg'],
    maxAltitude: '3842 ft',
    bestTime: 'October to March',
    highlights: ['Boat Ride in Koyna', 'Dense Jungle Trail', 'Babu Kada Cliff'],
    itinerary: [{ day: 1, title: 'Boat and Trek', description: 'Take a boat from Bamnoli, then trek through the jungle.' }],
    fitnessLevel: 'Moderate. Jungle trail can be humid.',
    packingList: ['Water', 'Snacks', 'Binoculars'],
    weather: { temp: '24°C', condition: 'Humid' },
    coordinates: [17.6614, 73.7114],
    route: [[17.6714, 73.7214], [17.6614, 73.7114]],
    waypoints: [{ name: 'Bamnoli', coordinates: [17.6714, 73.7214], type: 'base', description: 'Boat starting point' }]
  },
  {
    id: 'tikona',
    name: 'Tikona Fort Trek',
    tagline: 'The Triangular Fort',
    description: 'Tikona, also known as Vitandgad, is a dominant hill fort in Maval in western India. It is 3500 ft high and pyramidal in shape.',
    price: 4999,
    duration: '3 Days',
    difficulty: 'Easy',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/6f/98/47/6f9847bec3c27cae1c40a0ba0bfd030c.jpg',
    gallery: ['https://i.pinimg.com/736x/cd/5e/fe/cd5efe166eea5dce7c5a50163218b6d1.jpg'],
    maxAltitude: '3500 ft',
    bestTime: 'Year round',
    highlights: ['Pyramidal Shape', 'Pawna Dam View', 'Large Caves'],
    itinerary: [{ day: 1, title: 'Base to Summit', description: 'A short and easy climb from Tikona Peth.' }],
    fitnessLevel: 'Basic. Good for beginners.',
    packingList: ['Water', 'Hat', 'Walking shoes'],
    weather: { temp: '26°C', condition: 'Sunny' },
    coordinates: [18.6314, 73.5114],
    route: [[18.6414, 73.5214], [18.6314, 73.5114]],
    waypoints: [{ name: 'Tikona Peth', coordinates: [18.6414, 73.5214], type: 'base', description: 'Base village' }]
  },
  {
    id: 'tung',
    name: 'Tung Fort Trek',
    tagline: 'The Difficult Peak',
    description: 'Tung Fort is a hill fort in Pune district. It is known for its difficult climb and conical shape.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/1200x/62/59/ab/6259ab89d723795538d92d111de11cfc.jpg',
    gallery: ['https://i.pinimg.com/736x/d5/8b/e2/d58be2f8b9166af47da5d9224ca01d9b.jpg'],
    maxAltitude: '3527 ft',
    bestTime: 'September to March',
    highlights: ['Conical Shape', 'Pawna Dam View', 'Steep Steps'],
    itinerary: [{ day: 1, title: 'The Conical Climb', description: 'Start from Tungwadi and climb the steep path.' }],
    fitnessLevel: 'Moderate. Steep and narrow path at the top.',
    packingList: ['Water', 'Grip shoes', 'Energy bars'],
    weather: { temp: '24°C', condition: 'Windy' },
    coordinates: [18.6514, 73.4614],
    route: [[18.6614, 73.4714], [18.6514, 73.4614]],
    waypoints: [{ name: 'Tungwadi', coordinates: [18.6614, 73.4714], type: 'base', description: 'Base village' }]
  },
  {
    id: 'korigad',
    name: 'Korigad Fort Trek',
    tagline: 'The Monsoon Paradise',
    description: 'Korigad is a hill fort located about 20 km south of Lonavala. It is a very easy trek and perfect for monsoons.',
    price: 4999,
    duration: '3 Days',
    difficulty: 'Easy',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/ad/24/79/ad247979a62576d804d3b7e42d7a3271.jpg',
    gallery: ['https://i.pinimg.com/736x/d7/8a/84/d78a84ac0c63cdc5cfa56fc7cf0d0b08.jpg'],
    maxAltitude: '3028 ft',
    bestTime: 'Monsoon (July to September)',
    highlights: ['Large Plateau', 'Two Beautiful Lakes', 'Aamby Valley View'],
    itinerary: [{ day: 1, title: 'Easy Ascent', description: 'Start from Peth Shahpur and climb the wide steps.' }],
    fitnessLevel: 'Basic. Very easy climb.',
    packingList: ['Raincoat', 'Water', 'Snacks'],
    weather: { temp: '22°C', condition: 'Rainy' },
    coordinates: [18.6114, 73.3914],
    route: [[18.6214, 73.4014], [18.6114, 73.3914]],
    waypoints: [{ name: 'Peth Shahpur', coordinates: [18.6214, 73.4014], type: 'base', description: 'Base village' }]
  },
  {
    id: 'sudhagad',
    name: 'Sudhagad Fort Trek',
    tagline: 'The Well-Preserved Fort',
    description: 'Sudhagad is a hill fort situated near Pali. It is a very well-preserved fort and offers great views of the surrounding mountains.',
    price: 8999,
    duration: '5 Days',
    difficulty: 'Moderate',
    location: 'Maharashtra',
    image: 'https://i.pinimg.com/736x/4f/3a/24/4f3a240d948a933f03bf569d30c25de2.jpg',
    gallery: ['https://i.pinimg.com/736x/0c/ea/f7/0ceaf72fa47d5ada63a1dee060c2c279.jpg'],
    maxAltitude: '2030 ft',
    bestTime: 'September to March',
    highlights: ['Pali Ganpati View', 'Takmak Tok', 'Bhorai Devi Temple'],
    itinerary: [{ day: 1, title: 'Trek from Pali', description: 'Start from Thakurwadi and climb the stone steps.' }],
    fitnessLevel: 'Moderate. Some steep sections.',
    packingList: ['Water', 'Hat', 'Walking shoes'],
    weather: { temp: '24°C', condition: 'Pleasant' },
    coordinates: [18.5314, 73.3114],
    route: [[18.5414, 73.3214], [18.5314, 73.3114]],
    waypoints: [{ name: 'Thakurwadi', coordinates: [18.5414, 73.3214], type: 'base', description: 'Base village' }]
  }
];

export const BLOG_POSTS: BlogPost[] = [];
